name: Backend CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

run-name: Deploy version ${{ inputs.tag }} by ${{ github.actor }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      PACKAGE_VERSION: ${{ inputs.tag }}
      TF_VAR_random_integer: ${{ vars.TF_VAR_RANDOM_INTEGER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
      - name: Log in with Azure
        uses: azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy
        run: make backend-deploy
