name: Backend CI

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      PACKAGE_VERSION: "1.0.${{ github.run_number }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
      - name: Log in with Azure
        uses: azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set Package Version For Tags
        if: startsWith(github.ref, 'refs/tags/')
        # Extract {release_tag} from refs/tags/{release_tag} so it is used as package version
        run: echo "PACKAGE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build
        run: make backend-build
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        # Push only if branch is "main" or a tag is pushed
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: make backend-push
