name: Backend CI

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      PACKAGE_VERSION: "1.0.${{ github.run_number }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
      - name: Log in with Azure
        uses: azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build
        run: make backend-build
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: make backend-push
